development:
  adapter: postgresql
  encoding: utf8
  database: my_db3_name
  username: root
  password: root

production: 
  adapter: postgresql
  encoding: utf8
  database: my_db3_name
  username: root
  password: root